# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N', 'Common Notice'), ('W', 'Warning'), ('D', 'Danger')], max_length=1)),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, verbose_name='name of category')),
                ('url', models.CharField(max_length=80, unique=True, verbose_name='URL of Linked Page')),
            ],
            managers=[
                ('data_api', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('callout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ayase_blog.CallOut')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayase_blog.Category')),
            ],
            options={
                'ordering': ['-date'],
            },
            managers=[
                ('data_api', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
                ('about', models.TextField()),
            ],
        ),
    ]
